INSERT INTO "Kategorien" VALUES (1,'Smartphones');
INSERT INTO "Kategorien" VALUES (2,'Laptops');
INSERT INTO "Kategorien" VALUES (3,'Hardware');
INSERT INTO "Artikel" VALUES (1,'Apple iPhone 8','Genau was du willst, exakt was du brauchst.',529,1);
INSERT INTO "Artikel" VALUES (2,'Apple iPhone 11','Genau was du willst, exakt was du brauchst.',799.99,1);
INSERT INTO "Artikel" VALUES (3,'ASUS ROG STRIX NVIDIA GeForce RTX 2080 Ti OC','Grafikprozessorenfamilie: NVIDIA, GPU: GeForce RTX 2080 Ti, Prozessor-Taktfrequenz: 1350 MHz. Separater Grafik-Adapterspeicher: 11 GB, Grafikkartenspeichertyp: GDDR6, Speichertaktfrequenz: 14000 MHz. Maximale Auflösung: 7680 x 4320 Pixel. DirectX-Version:Prozessor Prozessor-Taktfrequenz : 1350 MHz GPU : GeForce RTX 2080 Ti Maximale Auflösung : 7680 x 4320 Pixel Parallele Verarbeitungstechnologie : Crossfire Maximale Displays pro Videokarte : 4 CUDA : Ja CUDA-Kerne',1329,3);
INSERT INTO "Artikel" VALUES (4,'HP 250 G7 6HM78ES 15,6"','Gutes Teil',299,2);
INSERT INTO "Artikel" VALUES (5,'Acer Aspire 5 (A514-52-58NK)','Mit dem Acer Aspire 5 (A514-52-58NK) kannst Du dank des schlanken, leichten Designs und der sandgestrahlten oberen Abdeckung aus Aluminium stilvoll reisen. Dieses schlanke Notebook ist lediglich 17,95 mm dünn und die glatte, angenehme Haptik vollendet das Premiumdesign mit edlem Look. Mit einer Akkulaufzeit von bis zu 12,5 Stunden ist Dein Notebook der perfekte Begleiter für den ganzen Tag.',699,2);
INSERT INTO "Artikel" VALUES (6,'Apple iPhone XR','Genau was du willst, exakt was du brauchst.',699,1);
INSERT INTO "Artikel" VALUES (7,'Asus ZenBook 14 UM431DA-AM058T','Kreativität. Stil. Innovation. Das sind Qualitätsmerkmale, die das elegante neue ZenBook 14 auszeichnen. In diesem superkompakten Meisterwerk ist alles so konzipiert, dass Sie die Freiheit haben, Ihre kreative Vision zu entdecken, einschließlich des atemberaubenden schmalen NanoEdge-Displays mit 86% Screen-to-Body-Ratio. Sie werden nicht nur die ungeheure Kraft im Inneren und die durchdachte Liebe zum Detail - wie das exklusive ErgoLift-Kippscharnier und das optionale NumberPad-Touchpad - schätzen, sondern auch die zeitlose Schönheit des Designs mit seinem edlen Finish Utopia Blue, das durch das stilvolle silberne Zierfeld noch verstärkt wird. Das ZenBook 14 wartet: Sind Sie bereit, Ihre kreative Vision zu verwirklichen?',555,2);
INSERT INTO "Artikel" VALUES (8,'Acer Aspire 3 A315-55G-54V9','Dünnes, hochwertiges Aluminum Design mit gebürsteten Aluminumcover bietet atemberaubende Optik...',555,2);
INSERT INTO "Artikel" VALUES (9,'Samsung Galaxy s10','Zehn Jahre Galaxy-Erfahrung sind in die Entwicklung des neuen Galaxy S10 geflossen – und das sieht man nicht nur, man spürt es auch. Das Ergebnis: Ein Smartphone, das schneller, intelligenter und hochwertiger ist als je ein Galaxy Smartphone zuvor. Hinter dem farbintensiven Infinity-O Display steckt mit dem Ultraschall-Fingerabdruckscanner ein Stück Zukunft, das begeistert. Das Galaxy S10 denkt mit. Es lernt dazu. Es teilt. Und es ist dafür gemacht, für jeden Alltag der passende Begleiter zu sein.',599.99,1);
INSERT INTO "Merkmale" VALUES (1,'Videowiedergabe','bis zu 14 Stunden',1);
INSERT INTO "Merkmale" VALUES (2,'Videowiedergabe','bis zu 16 Stunden',6);
INSERT INTO "Merkmale" VALUES (3,'Videowiedergabe','bis zu 17 Stunden',2);
INSERT INTO "Merkmale" VALUES (4,'Display','4,7'''' oder 5,5'''' Retina HD Display',1);
INSERT INTO "Merkmale" VALUES (5,'Kamera','Ein‑Kamera-System (Weitwinkel) oder Zwei‑Kamera-System (Weitwinkel, Teleobjektiv)',1);
INSERT INTO "Merkmale" VALUES (6,'Display','6,1'''' Liquid Retina HD Display',6);
INSERT INTO "Merkmale" VALUES (7,'Display','6,1'''' Liquid Retina HD Display',2);
INSERT INTO "Merkmale" VALUES (8,'Kamera','Ein‑Kamera-System (Weitwinkel)',6);
INSERT INTO "Merkmale" VALUES (9,'Kamera','Neues Zwei‑Kamera-System (Ultraweitwinkel, Weitwinkel',2);
INSERT INTO "Merkmale" VALUES (10,'Farbe','Weiß',9);
INSERT INTO "Merkmale" VALUES (11,'Monitor','Entspiegeltes 15,6"-Display mit einer Full HD Auflösung von 1920 x 1080 Pixeln',4);
INSERT INTO "Merkmale" VALUES (12,'RAM','8GB',4);
INSERT INTO "Merkmale" VALUES (13,'CPU','Intel I7 8700K',4);
INSERT INTO "Merkmale" VALUES (14,'Festplatte','500 GB SSD',4);
INSERT INTO "Merkmale" VALUES (15,'Auflösung','1920 x 1080 (Full HD Acer ComfyView™)',5);
INSERT INTO "Merkmale" VALUES (16,'Speicher','1.000 GB M.2 PCIe Solid-State-Drive (SSD)',5);
INSERT INTO "Merkmale" VALUES (17,'Grafik','Intel UHD Graphics 620',5);
INSERT INTO "Merkmale" VALUES (18,'RAM','8 GB DDR4 RAM',5);
INSERT INTO "Merkmale" VALUES (19,'RAM','8 GB LPDDR3',7);
INSERT INTO "Merkmale" VALUES (20,'CPU','AMD Ryzen 5 3500U Prozessor 4x 2.10 GHz',7);
INSERT INTO "Merkmale" VALUES (21,'Displaygröße','35,56 cm (14")',7);
INSERT INTO "Merkmale" VALUES (22,'RAM','8 GB DDR4',8);
INSERT INTO "Merkmale" VALUES (23,'CPU','Intel® Core™ i5 (8. Generation) 8265U Prozessor 4x 1,60 GHz',8);
INSERT INTO "Merkmale" VALUES (24,'Grafikkarte','GeForce MX230',8);
INSERT INTO "Merkmale" VALUES (25,'Modell/ Serie','ROG-STRIX-RTX2080TI-O11G-GAMING',3);
INSERT INTO "Merkmale" VALUES (26,'Gewicht','998g',3);
INSERT INTO "Merkmale" VALUES (27,'Arbeitsspeicher','11 GB',3);
INSERT INTO "Merkmale" VALUES (28,'Festplatte','11264 MB',3);
INSERT INTO "Merkmale" VALUES (29,'Prozessorgeschwindigkeit','1350 MHz',3);
INSERT INTO "Merkmale" VALUES (30,'Grafikkartenspeicher','GDDR6',3);
INSERT INTO "Merkmale" VALUES (31,'Interface','PCI-E',3);
INSERT INTO "Merkmale" VALUES (32,'Watt','650 Watt',3);
INSERT INTO "AspNetUsers" VALUES ('391c3801-312d-4b83-bd04-a6ece6a33cd4','d.mix@dvz-mv.de','D.MIX@DVZ-MV.DE','d.mix@dvz-mv.de','D.MIX@DVZ-MV.DE',1,'AQAAAAEAACcQAAAAEAJKe5wVtJZosRHKMQ5pQ4jcBbT2PBmuufRGWiaYE2vNL+w+pLlsMM5q9ErSvLpdOg==','B3ZKURE3TIKM3FWTZMUJ6UEU7ABP37IR','4a2fa1b9-68fe-46f4-9ba5-11bd7981a112',NULL,0,0,NULL,1,0,' Darius Mix','10178','Berlin','Alexanderplatz','1','2019-01-01 00:00:00');
INSERT INTO "AspNetUsers" VALUES ('5a182953-ef4b-4f87-b3a3-b51c22d3b88b','t.vinzing@dvz-mv.de','T.VINZING@DVZ-MV.DE','t.vinzing@dvz-mv.de','T.VINZING@DVZ-MV.DE',1,'AQAAAAEAACcQAAAAEMaqE0TOkc5O9Asgv38gwW5Nc/IBbH03MeWPYe4OzWo9aR1Xum6RaBxU1cw9s+RxTw==','ZF2WFNABN2B63TENWDSFIKSSDI2UNL2U','63d13574-48ac-48c0-9838-43370414de12',NULL,0,0,NULL,1,0,'Tim Vinzing','10178','Berlin','Alexanderplatz','1','2019-12-31 00:00:00');
INSERT INTO "Warenkoerbe" VALUES (1,'391c3801-312d-4b83-bd04-a6ece6a33cd4',1);
INSERT INTO "Warenkoerbe" VALUES (2,'5a182953-ef4b-4f87-b3a3-b51c22d3b88b',1);
INSERT INTO "Kommentare" VALUES (1,'Sehr geil',2,1,'391c3801-312d-4b83-bd04-a6ece6a33cd4');
INSERT INTO "Kommentare" VALUES (2,'noch geiler',3,2,'391c3801-312d-4b83-bd04-a6ece6a33cd4');
INSERT INTO "Kommentare" VALUES (3,'am geilsten',5,3,'5a182953-ef4b-4f87-b3a3-b51c22d3b88b');
INSERT INTO "Kommentare" VALUES (4,'finde ich auch sehr sehr geil',4,3,'391c3801-312d-4b83-bd04-a6ece6a33cd4');